// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class CartItem
{
    public int Id { get; set; }

    public int? CartId { get; set; }

    public int? ServiceId { get; set; }

    public int? ProductId { get; set; }

    public bool? IsDeleted { get; set; }

    public int? OrderHistoryId { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Product Product { get; set; }

    public virtual Service Service { get; set; }
}