// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public int? ServiceId { get; set; }

    public int? CustomerId { get; set; }

    public decimal? Rating { get; set; }

    public string FeedbackText { get; set; }

    public virtual User Customer { get; set; }

    public virtual Service Service { get; set; }
}