// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class PetType
{
    public int Id { get; set; }

    public int? EnvironmentId { get; set; }

    public string GeneralType { get; set; }

    public string SpecificType { get; set; }

    public virtual Environment Environment { get; set; }

    public virtual ICollection<Pet> Pets { get; set; } = new List<Pet>();
}