// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class SystemTransaction
{
    public int SystemTransactionId { get; set; }

    public int? FromId { get; set; }

    public int? ToId { get; set; }

    public decimal? Amount { get; set; }

    public string TransactionType { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}