// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class UserWallet
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public decimal? Amount { get; set; }

    public int? LoyaltyPoints { get; set; }

    public virtual User User { get; set; }
}