// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiCenter.Data.Models;

public partial class VeterinarianAvailability
{
    public int Id { get; set; }

    public int? VeterinarianId { get; set; }

    public DateTime? AvailableDate { get; set; }

    public DateTime? AvailableFromTime { get; set; }

    public DateTime? AvailableToTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Veterinarian Veterinarian { get; set; }
}